language: node_js
services:
  - docker
before_script:
  - mv src/datasources/db.datasource.test.json src/datasources/db.datasource.json
  - docker-compose up -d --build
  - sleep 30
script:
  - docker exec video-rental npm test
notifications:
  on_success: always
  on_failure: always