language: node_js
services:
  - docker
before_script:
  - cp .env.dist .env
  - docker-compose up -d --build
script:
  - docker-compose exec video-rental npm test
notifications:
  on_success: always
  on_failure: always